[package]
name = "saphir"
version = "0.9.3"
edition = "2018"
authors = ["richer <richer.arc@gmail.com>"]
description = "Yet another http server framework based on Hyper-rs"
documentation = "https://docs.rs/saphir"
homepage = "https://github.com/richerarc/saphir"
repository = "https://github.com/richerarc/saphir"
readme = "README.md"
keywords = ["hyper", "http", "server", "web"]
license = "MIT"

[features]

default = []
request_handler = []
https = ["rustls", "tokio-rustls"]

[dependencies]
log = "~0.4.6"
hyper = "~0.12.25"
hyperx = "~0.15.0"
http = "~0.1.16"
futures = "~0.1.25"
regex = "~1.1.2"
ansi_term = "~0.11.0"
tokio = "~0.1.18"
tokio-signal = "0.2.7"
parking_lot = "~0.8.0"
threadpool = "~1.7.1"
hashbrown = "~0.3.0"
num_cpus = "1.10"

rustls = { version = "~0.15.1", optional = true }
tokio-rustls = { version = "~0.9.1", optional = true }

[dev-dependencies]
serde_json = "1.0.39"
serde = "1.0.89"
serde_derive = "1.0.89"